# Jekyll configuration
# see : https://jekyllrb.com/docs/configuration/
title: La Haute-Marne Insoumise
email: insoumis52@gmail.com
email-cc: insoumis@pygmeeweb.com
description: Rejoignez la Haute-Marne Insoumise !

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://haute-marne-insoumise.fr" # the base hostname & protocol for your site, e.g. http://example.com

logoImage: phi-insoumis-rouille.svg

language: fr
timezone: "Europe/Paris"

twitter_username: F_insoumis52
facebook_username: HauteMarneinsoumiseJLM2017
github_username:  HauteMarneInsoumise
youtube_channel: UCZt8bymtSIzYl5r0ma7P-8A

google_analytics: UA-96117581-1

# default setup

defaults:
  -
    scope:
      type: pages
      path: "pages"
    values:
      permalink: /:basename/
      layout: default
  -
    scope:
      type: pages
      path: "pages/blog"
    values:
      permalink: /:path/:basename/
      layout: default

  -
    scope:
      type: posts
    values:
      permalink: /blog/:day-:month-:year/:title/
      layout: post
      author: La rédaction

excerpt_separator: "<!--more-->"

# twitter bootstrap grid classes used for display

# main row
main_row_class: "col-sm-6"


# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# ++++++++++++++++++++ Build settings +++++++++++++++++++++++
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Netlify cms config (see admin/config.yml)
netlify:
  backend:
    name: github
    repo: HauteMarneInsoumise/HauteMarneInsoumise.github.io
    branch: master

  publish_mode: editorial_workflow

  media_folder: "img/news"


# using twitter bootstrap
sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

  style: compressed

markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true
  # parse markdown inside block-level HTML tag
  parse_block_html: true

gems:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - scripts/*
  - bower.json
  - Readme.md

include:
  - _headers # netlify http headers setup
