---
# Netlify CMS Setup made in _config.yml
---

backend:
  name: {{ site.netlify.backend.name }}
  repo: {{ site.netlify.backend.repo }}
  branch: {{ site.netlify.backend.branch }}


publish_mode: {{ site.netlify.publish_mode }}


media_folder: {{ site.netlify.media_folder }}
